services:
    backend:
        image: vet-backend-supabase
        build:
            context: .
            dockerfile: Dockerfile
        container_name: Veterinaria-Backend
        environment:
            DATABASE_URL: ${DATABASE_URL}
        ports:
            - '8000:8000'
        volumes:
            - .:/app
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
        networks:
            default:
                aliases:
                    - backend

networks:
    default:
        external: true
        name: 'AppVeterinaria'
